name: CI

on:
  push:
  pull_request:

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install Poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: "1.8.3"
      - name: Install deps
        run: |
          poetry install
      - name: Lint
        run: |
          poetry run black --check src tests
          poetry run flake8
      - name: Tests
        run: |
          poetry run pytest -q